### ISSUE TITLE
Error in bmerge when doLeidenCluster

### ISSUE THREAD

**Issue by lijiacd985** [giotto-suite/Giotto#165]
Hi there, I was trying to replicate the pipeline using exactly the same on https://rubd.github.io/Giotto_site/articles/mini_visium.html

Everything runs smoothly, until "mini_visium <- doLeidenCluster(gobject = mini_visium, resolution = 0.4, n_iterations = 1000)"

there was error: Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  x.cell_ID is type environment which is not supported by data.table join

pDataDT(mini_visium)
                cell_ID nr_genes perc_genes total_expr
  1: AAAGGGATGTAGCAAG-1      226   38.24027   992.0223
  2: AAATGGCATGTCTTGT-1      283   47.88494  1123.8751
  3: AAATGGTCAATGTGCC-1      247   41.79357  1024.8760
  4: AAATTAACGGGTAGCT-1      221   37.39425   971.3199
  5: AACAACTGGTAGTTGC-1      306   51.77665  1157.2925
 ---                                                  
618: TTGTAATCCGTACTCG-1      313   52.96108  1179.7196
619: TTGTATCACACAGAAT-1      240   40.60914   999.6419
620: TTGTCGTTCAGTTACC-1      219   37.05584   991.4468
621: TTGTGGCCCTGACAGT-1      202   34.17936   924.0617
622: TTGTTCAGTGTGCTAC-1      232   39.25550  1019.5997

sessionInfo ("Giotto")
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
character(0)

other attached packages:
[1] Giotto_1.1.0

loaded via a namespace (and not attached):
 [1] reticulate_1.20      tidyselect_1.1.1     purrr_0.3.4         
 [4] lattice_0.20-44      colorspace_2.0-2     vctrs_0.3.8         
 [7] generics_0.1.0       htmltools_0.5.1.1    grDevices_4.0.3     
[10] utf8_1.2.2           rlang_0.4.11         R.oo_1.24.0         
[13] pillar_1.6.2         glue_1.4.2           DBI_1.1.1           
[16] R.utils_2.10.1       uwot_0.1.10          RcppZiggurat_0.1.6  
[19] RColorBrewer_1.1-2   matrixStats_0.60.0   lifecycle_1.0.0     
[22] munsell_0.5.0        gtable_0.3.0         R.methodsS3_1.8.1   
[25] htmlwidgets_1.5.3    leaps_3.1            labeling_0.4.2      
[28] irlba_2.3.3          parallel_4.0.3       fansi_0.5.0         
[31] Rfast_2.0.4          methods_4.0.3        Rcpp_1.0.7          
[34] scales_1.1.1         flashClust_1.01-2    DT_0.18             
[37] dbscan_1.1-8         scatterplot3d_0.3-41 magick_2.7.3        
[40] jsonlite_1.7.2       RSpectra_0.16-0      FNN_1.1.3           
[43] farver_2.1.0         ggplot2_3.3.5        stats_4.0.3         
[46] datasets_4.0.3       graphics_4.0.3       png_0.1-7           
[49] digest_0.6.27        Rtsne_0.15           dplyr_1.0.7         
[52] ggrepel_0.9.1        grid_4.0.3           cowplot_1.1.1       
[55] tools_4.0.3          magrittr_2.0.1       tibble_3.1.3        
[58] cluster_2.1.2        crayon_1.4.1         FactoMineR_2.4      
[61] pkgconfig_2.0.3      ellipsis_0.3.2       MASS_7.3-54         
[64] Matrix_1.3-4         data.table_1.14.0    utils_4.0.3         
[67] assertthat_0.2.1     base_4.0.3           R6_2.5.1            
[70] igraph_1.2.6         compiler_4.0.3      

Could you please help?

Thanks,

Jia

**Comment by RubD** [comment]
Hi Jia,

I think this is because you're using the first released version (1.1.0), which contained some bugs. If you re-install Giotto again your problem should be resolved.

```
remotes::install_github("RubD/Giotto")
```

Let me know how it goes!
Ruben

**Comment by lijiacd985** [comment]
Thanks Ruben.

I tried as you suggested. No luck. The same error still exist.

**Comment by RubD** [comment]
I'm unable to replicate your error. The example script works on my machine. Did you ran any other type of code or analysis prior to the example? 

And what is the version of `data.table`?

```
packageVersion('data.table')
```

Another potential problem could be that you don't have a proper Giotto environment to run python code (needed for the Leiden clustering).

Can you run the following command and let me know what you get?

```
checkGiottoEnvironment()
```

Thanks and sorry for the troubles.

**Comment by lijiacd985** [comment]
> packageVersion('data.table')
[1] ‘1.14.0’
> checkGiottoEnvironment()

 giotto environment found at 
 /Users/lijia/Library/r-miniconda/envs/giotto_env/bin/pythonw 
[1] TRUE

**Comment by Jluo21** [comment]
I installed Giotto yesterday and have the same issue now.
data.table ver: 1.14.2
giotto environment found at 
 C:/Users/JLuo/AppData/Local/r-miniconda\envs\giotto_env\python.exe 
[1] TRUE

**Comment by Jluo21** [comment]
I had the same issue when I just installed package 'community'. 
It works after I installed package 'python-louvain'.

**Comment by lijiacd985** [comment]
Thanks @Jluo21  suggestions. In my case, somehow in my giotto env, the leidenalg is missing. After conda install it, now it works now.

If the giotto have a conda install version, that will be great for the future users I think.

Thanks for the help @RubD  and @Jluo21 .

Happy new year 2022!

**Comment by RubD** [comment]
Thanks @Jluo21 for suggesting and finding a fix. It's a bit odd since the giotto environment should automatically installs all the necessary modules, and we more recently also fixed the version to ensure reproducibility.

FYI, the giotto suite branch (in development) has a couple of extra options to re-install/delete/check the r-miniconda and/or the giotto environemnt. See http://giottosuite.com/reference/index.html#section-giotto-environment .

Happy New Year!

**Comment by tdyoshida** [comment]
Hi @RubD, thanks for your fantastic work!

I encounter the same (I think) issue described above. When I tried to run the steps in [Visium Brain vignette](https://rubd.github.io/Giotto_site/articles/mouse_visium_brain_200918.html), I got an error when running the code in part 4.

```
visium_brain <- doLeidenCluster(gobject = visium_brain, resolution = 0.4, n_iterations = 1000)
```

```
Error in bmerge(i, x, leftcols, rightcols, roll, rollends, nomatch, mult,  : 
  x.cell_ID is type environment which is not supported by data.table join
```

I followed everything before this step as in the vignette, and successfully reproduced the results.
You mentioned above that version 1.1.0 contains some bugs, but it looks like v1.1.0 is the latest release on GitHub, and the following command installs 1.1.0
```
remotes::install_github("RubD/Giotto")

packageVersion("Giotto")
'1.1.0'
```

After reading comments by @Jluo21 and @lijiacd985, I checked 'leidenalg' and 'python-louvain' in my giotto_env.

```
# Name                    Version                   Build  Channel
leidenalg                 0.8.7            py36hefe7e0e_0    conda-forge
python-louvain            0.15               pyhd8ed1ab_1    conda-forge
```

I'm including some more information below. I truly appreciate your help!

```
Giotto:::checkGiottoEnvironment()
giotto environment found at 
/Users/tdyoshida/Library/r-miniconda/envs/giotto_env/bin/pythonw 
[1] TRUE
```

```
Giotto:::showProcessingSteps(visium_brain)
 0_subset 

 1_subset 

 2_filter 

 3_normalize 

 4_gene_stats 

 5_cell_stats 

 6_hvg 
	 name info:  hvg 

 7_pca 
	 name info:  pca 

 8_umap 
	 name info:  pca umap 

 9_tsne 
	 name info:  pca tsne 

 10_nn_network 
	 name info:  pca sNN.pca 
```

```
str(visium_brain, max.level = 3)
Formal class 'giotto' [package "Giotto"] with 19 slots
  ..@ raw_exprs          :Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  ..@ norm_expr          : num [1:14814, 1:2698] 0 0 0 0.364 0.364 ...
  .. ..- attr(*, "dimnames")=List of 2
  ..@ norm_scaled_expr   : num [1:14814, 1:2698] -0.263 -0.28 -0.284 0.2 0.732 ...
  .. ..- attr(*, "dimnames")=List of 2
  ..@ custom_expr        : NULL
  ..@ spatial_locs       :Classes ‘data.table’ and 'data.frame':	2698 obs. of  3 variables:
  .. ..$ sdimx  : int [1:2698] 8229 4169 2518 7678 3137 4100 2518 5614 6646 5270 ...
  .. ..$ sdimy  : int [1:2698] -7237 -1611 -8315 -2927 -6280 -7477 -5681 -1970 -5441 -9272 ...
  .. ..$ cell_ID: chr [1:2698] "AAACAAGTATCTCCCA-1" "AAACAATCTACTAGCA-1" "AAACACCAATAACTGC-1" "AAACAGAGCGACTCCT-1" ...
  .. ..- attr(*, ".internal.selfref")=<externalptr> 
  ..@ cell_metadata      :Classes ‘data.table’ and 'data.frame':	2698 obs. of  7 variables:
  .. ..$ cell_ID   : chr [1:2698] "AAACAAGTATCTCCCA-1" "AAACAATCTACTAGCA-1" "AAACACCAATAACTGC-1" "AAACAGAGCGACTCCT-1" ...
  .. ..$ in_tissue : int [1:2698] 1 1 1 1 1 1 1 1 1 1 ...
  .. ..$ array_row : int [1:2698] 50 3 59 14 42 52 37 6 35 67 ...
  .. ..$ array_col : int [1:2698] 102 43 19 94 28 42 19 64 79 59 ...
  .. ..$ nr_genes  : num [1:2698] 5215 3637 6236 4495 5952 ...
  .. ..$ perc_genes: num [1:2698] 35.2 24.6 42.1 30.3 40.2 ...
  .. ..$ total_expr: num [1:2698] 3795 3022 3571 3556 3594 ...
  .. ..- attr(*, ".internal.selfref")=<externalptr> 
  .. ..- attr(*, "sorted")= chr "cell_ID"
  ..@ gene_metadata      :Classes ‘data.table’ and 'data.frame':	14814 obs. of  7 variables:
  .. ..$ gene_ID      : chr [1:14814] "Xkr4" "Gm19938" "Sox17" "Mrpl15" ...
  .. ..$ nr_cells     : num [1:14814] 251 296 315 1817 1355 ...
  .. ..$ perc_cells   : num [1:14814] 9.3 11 11.7 67.3 50.2 ...
  .. ..$ total_expr   : num [1:14814] 71.7 89.7 96.5 814.5 488 ...
  .. ..$ mean_expr    : num [1:14814] 0.0266 0.0332 0.0358 0.3019 0.1809 ...
  .. ..$ mean_expr_det: num [1:14814] 0.286 0.303 0.306 0.448 0.36 ...
  .. ..$ hvg          : chr [1:14814] "no" "no" "no" "no" ...
  .. ..- attr(*, ".internal.selfref")=<externalptr> 
  ..@ cell_ID            : Named chr [1:2698] "AAACAAGTATCTCCCA-1" "AAACAATCTACTAGCA-1" "AAACACCAATAACTGC-1" "AAACAGAGCGACTCCT-1" ...
  .. ..- attr(*, "names")= chr [1:2698] "2" "3" "4" "5" ...
  ..@ gene_ID            : Named chr [1:14814] "Xkr4" "Gm19938" "Sox17" "Mrpl15" ...
  .. ..- attr(*, "names")= chr [1:14814] "1" "3" "6" "9" ...
  ..@ spatial_network    : NULL
  ..@ spatial_grid       : NULL
  ..@ spatial_enrichment : NULL
  ..@ dimension_reduction:List of 1
  .. ..$ cells:List of 3
  ..@ nn_network         :List of 1
  .. ..$ sNN:List of 1
  ..@ images             :List of 1
  .. ..$ image:List of 4
  .. .. ..- attr(*, "class")= chr [1:2] "list" "imageGiottoObj"
  ..@ parameters         :List of 11
  .. ..$ 0_subset     : Named int [1:2] 2290 0
  .. .. ..- attr(*, "names")= chr [1:2] "cells removed" "genes removed"
  .. ..$ 1_subset     : Named int [1:2] 4 7311
  .. .. ..- attr(*, "names")= chr [1:2] "cells removed" "genes removed"
  .. ..$ 2_filter     : Named chr [1:4] "raw" "1" "1000" "50"
  .. .. ..- attr(*, "names")= chr [1:4] "used expression values" "gene expression threshold" "minimum # of genes detected per cell" "minimum times a gene is detected over all cells"
  .. ..$ 3_normalize  : Named chr [1:9] "standard" "yes" "6000" "yes" ...
  .. .. ..- attr(*, "names")= chr [1:9] "normalization method" "normalized to library size" "scalefactor" "log-normalized" ...
  .. ..$ 4_gene_stats : Named chr [1:2] "normalized" "0"
  .. .. ..- attr(*, "names")= chr [1:2] "expression values used" "detection_threshold"
  .. ..$ 5_cell_stats : Named chr [1:2] "normalized" "0"
  .. .. ..- attr(*, "names")= chr [1:2] "expression values used" "detection_threshold"
  .. ..$ 6_hvg        : Named chr [1:11] "cov_groups" "normalized" "scaled" "custom" ...
  .. .. ..- attr(*, "names")= chr [1:11] "method used" "expression values1" "expression values2" "expression values3" ...
  .. ..$ 7_pca        : Named chr [1:10] "cells" "normalized" "scaled" "custom" ...
  .. .. ..- attr(*, "names")= chr [1:10] "reduction type:" "expression values1" "expression values2" "expression values3" ...
  .. ..$ 8_umap       : Named chr [1:14] "cells" "pca" "pca" "10" ...
  .. .. ..- attr(*, "names")= chr [1:14] "reduction type" "dimension reduction used" "name for dimension reduction" "dimensions used" ...
  .. ..$ 9_tsne       : Named chr [1:13] "cells" "pca" "pca" "10" ...
  .. .. ..- attr(*, "names")= chr [1:13] "reduction type" "dimension reduction used" "name for dimension reduction" "dimensions used" ...
  .. ..$ 10_nn_network: Named chr [1:12] "sNN" "pca" "pca" "10" ...
  .. .. ..- attr(*, "names")= chr [1:12] "nearest-neighbour type" "dimension reduction used" "name for dimension reduction" "dimensions used" ...
  ..@ instructions       :List of 11
  .. ..$ python_path: chr "/Users/tdyoshida/Library/r-miniconda/envs/giotto_env/bin/pythonw"
  .. ..$ show_plot  : logi FALSE
  .. ..$ return_plot: logi TRUE
  .. ..$ save_plot  : logi TRUE
  .. ..$ save_dir   : chr "R/Giotto/"
  .. ..$ plot_format: chr "png"
  .. ..$ dpi        : num 300
  .. ..$ units      : chr "in"
  .. ..$ height     : num 9
  .. ..$ width      : num 9
  .. ..$ is_docker  : logi FALSE
  ..@ offset_file        : NULL
  ..@ OS_platform        : chr "unix"
```

```
sessionInfo()

R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.14.2 Giotto_1.1.0      forcats_0.5.1     stringr_1.4.0     dplyr_1.0.8       purrr_0.3.4      
 [7] readr_2.1.2       tidyr_1.2.0       tibble_3.1.6      ggplot2_3.3.5     tidyverse_1.3.1  

loaded via a namespace (and not attached):
 [1] matrixStats_0.61.0   fs_1.5.2             lubridate_1.8.0      RColorBrewer_1.1-2   httr_1.4.2          
 [6] rprojroot_2.0.2      tools_4.1.1          backports_1.4.1      DT_0.21              utf8_1.2.2          
[11] R6_2.5.1             uwot_0.1.11          DBI_1.1.2            colorspace_2.0-3     withr_2.5.0         
[16] prettyunits_1.1.1    processx_3.5.2       tidyselect_1.1.2     curl_4.3.2           compiler_4.1.1      
[21] textshaping_0.3.6    cli_3.2.0            rvest_1.0.2          flashClust_1.01-2    xml2_1.3.3          
[26] labeling_0.4.2       scales_1.1.1         callr_3.7.0          systemfonts_1.0.4    digest_0.6.29       
[31] dbscan_1.1-10        rmarkdown_2.13       R.utils_2.11.0       pkgconfig_2.0.3      htmltools_0.5.2     
[36] dbplyr_2.1.1         fastmap_1.1.0        FactoMineR_2.4       htmlwidgets_1.5.4    rlang_1.0.2         
[41] readxl_1.3.1         rstudioapi_0.13      FNN_1.1.3            generics_0.1.2       farver_2.1.0        
[46] jsonlite_1.8.0       R.oo_1.24.0          magrittr_2.0.2       leaps_3.1            Matrix_1.4-0        
[51] Rcpp_1.0.8.3         munsell_0.5.0        fansi_1.0.2          reticulate_1.24      lifecycle_1.0.1     
[56] RcppZiggurat_0.1.6   R.methodsS3_1.8.1    scatterplot3d_0.3-41 stringi_1.7.6        yaml_2.3.5          
[61] MASS_7.3-55          pkgbuild_1.3.1       Rtsne_0.15           grid_4.1.1           parallel_4.1.1      
[66] ggrepel_0.9.1        crayon_1.5.0         lattice_0.20-45      haven_2.4.3          cowplot_1.1.1       
[71] hms_1.1.1            magick_2.7.3         ps_1.6.0             knitr_1.37           pillar_1.7.0        
[76] igraph_1.2.11        reprex_2.0.1         glue_1.6.2           evaluate_0.15        remotes_2.4.2       
[81] modelr_0.1.8         png_0.1-7            vctrs_0.3.8          tzdb_0.2.0           cellranger_1.1.0    
[86] gtable_0.3.0         assertthat_0.2.1     xfun_0.30            Rfast_2.0.6          broom_0.7.12        
[91] RSpectra_0.16-0      ragg_1.2.2           cluster_2.1.2        ellipsis_0.3.2       here_1.0.1  
```
